name: YouTube Shorts to Facebook (Link Only)

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests isodate

      - name: Run script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          FB_PAGE_ID: ${{ secrets.PAGE_ID }}
          FB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: python script.py

      - name: Commit last video file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add posted_ids.txt

          git commit -m "update posted list" || echo "no changes"

          git pull origin main --rebase

          git push
