name: Daily YouTube to Facebook

on:
  schedule:
    - cron: "0 6 * * *"  # كل يوم 6 صباحًا
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests yt-dlp isodate

      - name: Run script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          FB_PAGE_ID: ${{ secrets.PAGE_ID }}
          FB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: python script.py
